---


- name: 'Pi-hole related tasks'
  tags:
    - dnscrypt
    - dnscrypt_pihole
  block:
    - name: '[pihole] Collect unique IP addresses and ports from PIHOLE_DNS entries'
      ansible.builtin.shell: "grep '^PIHOLE_DNS_' /etc/pihole/setupVars.conf | grep -oP '(?<=PIHOLE_DNS_\\d=).*' | sort -u"
      register: unique_pihole_dns_ips
      ignore_errors: true
      changed_when: false

    - name: '[pihole] Remove all PIHOLE_DNS_ lines from /etc/pihole/setupVars.conf, including commented lines'
      ansible.builtin.lineinfile:
        path: /etc/pihole/setupVars.conf
        regexp: '^\s*#?\s*PIHOLE_DNS_'
        state: absent
        backup: yes

    - name: '[pihole] Add PIHOLE_DNS_1 entry'
      ansible.builtin.lineinfile:
        path: /etc/pihole/setupVars.conf
        line: 'PIHOLE_DNS_1={{ dnscrypt_ipv4_address }}#{{ dnscrypt_port }}'
        state: present
        backup: true
      notify: Restart pihole-FTL

    - name: '[pihole] Add remaining PIHOLE_DNS_ entries'
      ansible.builtin.lineinfile:
        path: /etc/pihole/setupVars.conf
        line: 'PIHOLE_DNS_{{ item_index + 2 }}={{ item }}'
        state: present
        backup: true
      loop: "{{ (unique_pihole_dns_ips.stdout_lines | reject('equalto', dnscrypt_ipv4_address + '#' + dnscrypt_port | string) | list) }}"
      loop_control:
        index_var: item_index
      notify: Restart pihole-FTL
      when:
        - unique_pihole_dns_ips.stdout_lines | reject('equalto', dnscrypt_ipv4_address + '#' + dnscrypt_port | string) | list | length > 0
        - item_index < 3

    - name: '[pihole] Get current server entries in /etc/dnsmasq.d/01-pihole.conf'
      ansible.builtin.command: grep '^server=' /etc/dnsmasq.d/01-pihole.conf
      register: dnsmasq_server_entries
      ignore_errors: true
      changed_when: false

    - name: '[pihole] Remove all server= lines from /etc/dnsmasq.d/01-pihole.conf, including commented lines'
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.d/01-pihole.conf
        regexp: '^\s*#?\s*server='
        state: absent
        backup: true

    - name: '[pihole] Add server entry'
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.d/01-pihole.conf
        line: 'server={{ dnscrypt_ipv4_address }}#{{ dnscrypt_port }}'
        state: present
        backup: true
      notify: Restart pihole-FTL

    - name: '[pihole] Add remaining server entries'
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.d/01-pihole.conf
        line: 'server={{ item }}'
        state: present
        backup: true
      loop: "{{ (dnsmasq_server_entries.stdout_lines | reject('equalto', dnscrypt_ipv4_address + '#' + dnscrypt_port | string) | list) }}"
      loop_control:
        index_var: item_index
      notify: Restart pihole-FTL
      when:
        - dnsmasq_server_entries.stdout_lines | reject('equalto', dnscrypt_ipv4_address + '#' + dnscrypt_port | string) | list | length > 0
        - item_index < 3
