---
- name: '[pihole] Remove duplicate `PIHOLE_DNS_[0-9]` entries in /etc/pihole/setupVars.conf'
  ansible.builtin.lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: '^PIHOLE_DNS_[0-9]='
    state: absent
    backup: true
  become: true
  notify: Restart pihole-FTL
  tags:
    - dnscrypt
    - dnscrypt_pihole

- name: '[pihole] Ensure dnscrypt server is set in /etc/pihole/setupVars.conf'
  ansible.builtin.lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: '^PIHOLE_DNS_[0-9]='
    line: 'PIHOLE_DNS_1={{ dnscrypt_ipv4_address }}#{{ dnscrypt_port }}'
    state: present
  become: true
  notify: Restart pihole-FTL
  tags:
    - dnscrypt
    - dnscrypt_pihole

- name: '[pihole] Remove duplicate `server=` entries in /etc/dnsmasq.d/01-pihole.conf'
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.d/01-pihole.conf
    regexp: '^server='
    line: ''
    state: absent
    backup: true
  become: true
  notify: Restart pihole-FTL
  tags:
    - dnscrypt
    - dnscrypt_pihole

- name: '[pihole] Ensure unique dnscrypt server is configured in /etc/dnsmasq.d/01-pihole.conf'
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.d/01-pihole.conf
    regexp: '^server={{ dnscrypt_ipv4_address }}#{{ dnscrypt_port }}'
    line: 'server={{ dnscrypt_ipv4_address }}#{{ dnscrypt_port }}'
    state: present
  become: true
  notify: Restart pihole-FTL
  tags:
    - dnscrypt
    - dnscrypt_pihole
