---
# handlers file for ansible-dnscrypt

# DNSMasq
- name: Restart pihole-FTL
  ansible.builtin.service:
    name: pihole-FTL
    state: restarted
  become: true
  when: dnscrypt_on_pihole

- name: Restart dnscrypt-proxy service
  ansible.builtin.service:
    name: dnscrypt-proxy
    state: restarted
  when: not dnscrypt_systemd.stat.exists
  become: true

- name: Stop dnscrypt-proxy service
  ansible.builtin.service:
    name: dnscrypt-proxy
    state: stopped
  become: true
  listen: Restart dnscrypt-proxy.socket systemd unit
  when: dnscrypt_systemd.stat.exists

- name: Make sure dnscrypt-proxy.service is stopped before restarting dnscrypt-proxy.socket
  ansible.builtin.service:
    name: dnscrypt-proxy.service
    state: stopped
  become: true
  listen: Restart dnscrypt-proxy.socket systemd unit

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  listen: Restart dnscrypt-proxy.socket systemd unit
  when: dnscrypt_systemd.stat.exists

- name: Restart dnscrypt-proxy.socket
  ansible.builtin.service:
    name: dnscrypt-proxy.socket
    enabled: true
    state: restarted
  become: true
  listen: Restart dnscrypt-proxy.socket systemd unit
  when: dnscrypt_systemd.stat.exists

- name: Restart dnscrypt-proxy.socket
  ansible.builtin.service:
    name: dnscrypt-proxy.socket
    enabled: true
    state: restarted
  become: true
  listen: Restart dnscrypt-proxy.socket systemd unit
  when: dnscrypt_systemd.stat.exists
