---
# handlers file for ansible-dnscrypt

# DNSMasq
- name: Restart pihole-FTL
  ansible.builtin.service:
    name: pihole-FTL
    state: restarted
  when: dnscrypt_on_pihole

# No SystemD
- name: Run 'dnscrypt-proxy -service restart'
  ansible.builtin.command:
    cmd: "{{ dnscrypt_bin }} -service restart"
  changed_when: false
  when: not dnscrypt_systemd.stat.exists

# SystemD
- name: Make sure built-in dnscrypt-proxy service is stopped, running 'dnscrypt-proxy -service stop'
  ansible.builtin.command:
    cmd: "{{ dnscrypt_bin }} -service stop"
    creates: /var/run/dnscrypt-proxy.pid
  listen: Restart dnscrypt-proxy.socket systemd unit
  when: dnscrypt_systemd.stat.exists

- name: Make sure dnscrypt-proxy.service is stopped before restarting dnscrypt-proxy.socket
  ansible.builtin.service:
    name: dnscrypt-proxy.service
    state: stopped
  listen: Restart dnscrypt-proxy.socket systemd unit
  when: dnscrypt_systemd.stat.exists

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Restart dnscrypt-proxy.socket systemd unit
  when: dnscrypt_systemd.stat.exists

- name: Restart dnscrypt-proxy.socket
  ansible.builtin.service:
    name: dnscrypt-proxy.socket
    enabled: true
    state: restarted
  listen: Restart dnscrypt-proxy.socket systemd unit
  when: dnscrypt_systemd.stat.exists
...
